server:
  port: 9000

spring:
  # 1. LDAP ??? ??? ???? Property ? ???? ???? (CoP, Configuration of Properties)
  ldap: # -> ? ???? LdapContextSource ???? ????. (LDAP Init ? ??? ?? ???)
  # LDAP ??? ??? ??. ?? ??? ??? ??(,)? ?? ?? ?? ??
  urls: ldap://192.168.0.2:389
  # LDAP ?????? ??? ?? DN(Base Distinguished Name)
  base: dc=wooks-space,dc=me
  # ??? ?? - bind ???? ??? ??? ? ??/?? ??? ??? ??
  username: cn=admin,dc=wooks-space,dc=me
  password: 1q2w#E$R